pipeline {

 agent any

 stages {

  stage('Clone Repository') {

   steps {
    git 'https://github.com/yourusername/devops-pipeline.git'
   }

  }

  stage('Build Docker Image') {

   steps {
    sh 'docker build -t devops-demo .'
   }

  }

  stage('Run Ansible Deployment') {

   steps {
    sh 'ansible-playbook ansible/deploy.yml'
   }

  }

 }

}